-- MatriGuard dashboard: the ten articles the website listed before the
-- dashboard existed. Run once, after schema.sql, in the same SQL tab.
-- INSERT IGNORE: running it again skips posts that are already there.
--
-- Each body is only its excerpt; the full articles still need writing in
-- the editor. Their covers point at images the website already ships.

INSERT IGNORE INTO posts
  (id, slug, title, excerpt, category, cover_image, cover_alt, cover_position,
   content_html, meta_description, status, published_at, reading_minutes, created_at, updated_at)
VALUES
  ('seed-01', 'what-to-check-before-you-say-yes', 'What is worth checking before you say yes', 'Families often ask us what matters most. In practice it comes down to six things, and four of them can be settled in under a week.', 'Where to start', '/images/image3.png', '', 'center', '<p>Families often ask us what matters most. In practice it comes down to six things, and four of them can be settled in under a week.</p>', '', 'published', '2026-09-02', 1, '2026-10-01 00:00:00.000', '2026-10-01 00:00:00.000'),
  ('seed-02', 'red-flags-in-a-matrimonial-profile', 'Red flags in an online matrimonial profile', 'Online matchmaking made it easier to meet families, and easier for a few people to say things that are not true. Here is what tends to give them away.', 'Safety', '/images/image5.png', '', 'center', '<p>Online matchmaking made it easier to meet families, and easier for a few people to say things that are not true. Here is what tends to give them away.</p>', '', 'published', '2026-08-12', 1, '2026-10-01 00:00:00.000', '2026-10-01 00:00:00.000'),
  ('seed-03', 'a-job-letter-is-not-proof-of-income', 'Why a job letter is not proof of income', 'A letter on company paper is easy to produce. What actually confirms a salary is the dull paperwork nobody thinks to ask for.', 'Money', '/images/image4.png', '', 'center', '<p>A letter on company paper is easy to produce. What actually confirms a salary is the dull paperwork nobody thinks to ask for.</p>', '', 'published', '2026-08-05', 1, '2026-10-01 00:00:00.000', '2026-10-01 00:00:00.000'),
  ('seed-04', 'what-a-report-contains', 'What a background report actually contains', 'Every point is marked confirmed, not confirmed, or not found, and what we heard locally is kept separate from what we verified ourselves.', 'Your report', '/images/hero/hero-4.webp', '', 'center 40%', '<p>Every point is marked confirmed, not confirmed, or not found, and what we heard locally is kept separate from what we verified ourselves.</p>', '', 'published', '2026-07-28', 1, '2026-10-01 00:00:00.000', '2026-10-01 00:00:00.000'),
  ('seed-05', 'asking-about-an-earlier-marriage', 'Asking about an earlier marriage, without causing offence', 'It is the question families most dread raising. It is also the one that most often changes a decision, so it is worth asking well.', 'Families', '/images/hero/hero-1.webp', '', '75% center', '<p>It is the question families most dread raising. It is also the one that most often changes a decision, so it is worth asking well.</p>', '', 'published', '2026-07-14', 1, '2026-10-01 00:00:00.000', '2026-10-01 00:00:00.000'),
  ('seed-06', 'degrees-that-do-not-exist', 'Degrees that do not exist, and how we spot them', 'A convincing certificate from a university that never awarded it. The registrar\'s office usually settles the question in a day or two.', 'Documents', '/images/image2.png', '', 'center', '<p>A convincing certificate from a university that never awarded it. The registrar\'s office usually settles the question in a day or two.</p>', '', 'published', '2026-06-30', 1, '2026-10-01 00:00:00.000', '2026-10-01 00:00:00.000'),
  ('seed-07', 'what-we-cannot-check', 'What we cannot check, and why we tell you', 'We do not tap phones or open private accounts. A clear “we could not confirm this” is worth more to you than a soft answer.', 'How we work', '/images/image1.png', '', 'center', '<p>We do not tap phones or open private accounts. A clear “we could not confirm this” is worth more to you than a soft answer.</p>', '', 'published', '2026-06-18', 1, '2026-10-01 00:00:00.000', '2026-10-01 00:00:00.000'),
  ('seed-08', 'how-long-a-check-takes', 'How long a check takes, honestly', 'Two to four working days for documents, up to a fortnight for conduct enquiries. Here is what actually makes a case run long.', 'How we work', '/images/hero/hero-3.webp', '', '65% 45%', '<p>Two to four working days for documents, up to a fortnight for conduct enquiries. Here is what actually makes a case run long.</p>', '', 'published', '2026-06-04', 1, '2026-10-01 00:00:00.000', '2026-10-01 00:00:00.000'),
  ('seed-09', 'checking-a-family-not-just-a-person', 'Checking a family, not just a person', 'A proposal is rarely about one person alone. What we look at when the real question is about the household behind them.', 'Families', '/images/image3.png', '', 'center', '<p>A proposal is rarely about one person alone. What we look at when the real question is about the household behind them.</p>', '', 'published', '2026-05-21', 1, '2026-10-01 00:00:00.000', '2026-10-01 00:00:00.000'),
  ('seed-10', 'a-report-you-did-not-want', 'What to do with a report you did not want', 'Sometimes the findings confirm the worry rather than settle it. Families usually have more options open to them than they think.', 'Your report', '/images/image5.png', '', 'center', '<p>Sometimes the findings confirm the worry rather than settle it. Families usually have more options open to them than they think.</p>', '', 'published', '2026-05-07', 1, '2026-10-01 00:00:00.000', '2026-10-01 00:00:00.000');
